const web3StorageToken = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6ZXRocjoweDJBRDMxMjkxRkZBNDdjRmYzQzAyMzgyMDZlMmMyRjAyMEQ2ZGJhMEYiLCJpc3MiOiJ3ZWIzLXN0b3JhZ2UiLCJpYXQiOjE2NTk5NzQxNzg1MjQsIm5hbWUiOiJTTEJfdG9rZW4ifQ.gbx1yU3nuHQAykVNcTP2vwCHaQkvufyPD6dRPNSqCek';

export default web3StorageToken;